# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ellen galperin
email: egalperi@thoughtworks.com
description: >
  Ellen currently resides in New York City where she works for
  ThoughtWorks as a developer. She has a passion for clear & concise code,
  human centered design, and using technology as a tool for social and economic justice.
  When she is not playing games on her 3DS or binging documentaries on Netflix, she can be found
  exploring the New York food scene.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 8bytewonder
github_username:  galperie

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
